export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const ADD_INGRIDIENTS = 'ADD_INGRIDIENTS';